import plaatsnamen from '@/data/plaatsnames'
import styles from '@/styles/Home.module.css'
import { GetStaticPropsContext } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import slugify from 'slugify'

type Props = {
    slug: string
}

export async function getStaticPaths() {
    return {
        paths: plaatsnamen.map((plaatnaam: string) => ({
            params: {
                slug: slugify(plaatnaam)
            }
        })), // See the "paths" section below
        fallback: true //, false or "blocking" // See the "fallback" section below
    };
}

export async function getStaticProps({ params }: GetStaticPropsContext<Props>) {
    return {
        props: {
            ...params
        }, // will be passed to the page component as props
    }
}

export default function Page({ slug }: Props) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.grid}>
                    <ul>
                        {plaatsnamen.map((plaatnaam: string) => (
                            <li key={slugify(plaatnaam)}>
                                <Link href={slugify(plaatnaam)}>
                                    {plaatnaam}
                                </Link>
                            </li>
                        ))}
                    </ul>
                </div>
            </main>
        </>
    )
}
