import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { GetStaticPropsContext } from 'next'
import plaatsnamen from '@omrijden.nl/plaatsnamen'
import Link from 'next/link'
import slugify from 'slugify'

type Props = {
    slug: string
}

export async function getStaticPaths() {
    return {
        paths: plaatsnamen.map((plaatnaam: string) => ({
            params: {
                slug: slugify(plaatnaam)
            }
        })), // See the "paths" section below
        fallback: true //, false or "blocking" // See the "fallback" section below
    };
}

export async function getStaticProps({ params }: GetStaticPropsContext<Props>) {
    return {
        props: {
            ...params
        }, // will be passed to the page component as props
    }
}

export default function Page({ slug }: Props) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.description}>
                    <h1>Verkeersituatie in {slug}</h1>
                </div>

                <ul>
                    {plaatsnamen.map((plaatnaam: string) => (
                        <li key={slugify(plaatnaam)}>
                            <Link href={slugify(plaatnaam)}>
                                {plaatnaam}
                            </Link>
                        </li>
                    ))}
                </ul>


                <div className={styles.grid}>
                    <a
                        href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        className={styles.card}
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <h2>
                            Docs <span>-&gt;</span>
                        </h2>
                        <p>
                            Find in-depth information about Next.js features and&nbsp;API.
                        </p>
                    </a>

                    <a
                        href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        className={styles.card}
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <h2>
                            Learn <span>-&gt;</span>
                        </h2>
                        <p>
                            Learn about Next.js in an interactive course with&nbsp;quizzes!
                        </p>
                    </a>

                    <a
                        href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        className={styles.card}
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <h2>
                            Templates <span>-&gt;</span>
                        </h2>
                        <p>
                            Discover and deploy boilerplate example Next.js&nbsp;projects.
                        </p>
                    </a>

                    <a
                        href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        className={styles.card}
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <h2>
                            Deploy <span>-&gt;</span>
                        </h2>
                        <p>
                            Instantly deploy your Next.js site to a shareable URL
                            with&nbsp;Vercel.
                        </p>
                    </a>
                </div>
            </main>
        </>
    )
}
