import plaatsnamen from '@/data/plaatsnames'
import styles from '@/styles/Home.module.css'
import Head from 'next/head'
import Link from 'next/link'
import slugify from 'slugify'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.grid}>
          <ul>
            {plaatsnamen.map((plaatnaam: string) => (
              <li key={slugify(plaatnaam)}>
                <Link href={slugify(plaatnaam)}>
                  {plaatnaam}
                </Link>
              </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  )
}
