name = "ndw-incidents"
main = "src/index.ts"
compatibility_date = "2023-04-22"
usage_model = "bundled"
logpush = true

kv_namespaces = [
  { binding = "STORE", id = "40310adcd3604e36b90d859c692c8cd5", preview_id = "40310adcd3604e36b90d859c692c8cd5" },
]

[triggers]
crons = ["*/1 * * * *"]